version: '3'

services:

  myapp-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scooterservice
      - MYSQL_USER=root
      - MYSQL_PASSWORD=qwerty123
    ports:
      - 3306:3306

  myapp-main:
    image: test-img
    restart: on-failure
    depends_on:
      - myapp-mysql
    ports:
      - 8088:8088
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=qwerty123
      - DATABASE_NAME=scooterservice
      - DATABASE_PORT=3306